[package]
name = "round_robin_tui"
version = "0.1.0"
edition = "2024"

[dependencies]
round_robin = { path = ".." }
clap.workspace = true
toml.workspace = true
log.workspace = true
indexmap.workspace = true
indicatif.workspace = true
itertools.workspace = true
ndarray.workspace = true

color-eyre = "0.6.5"
crossterm = "0.29.0"
ratatui = "0.29.0"
tui-logger = "0.17.3"
